services:
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:
      - ./apps/backend/.env
    environment:
      - DAGSTER_HOME=/app/.dagster
    volumes:
      - ./apps/backend/.dagster:/app/.dagster
    depends_on:
      mongodb:
        condition: service_healthy
    restart: unless-stopped

  dagster-webserver:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    command: dagster-webserver -h 0.0.0.0 -p 3001 -w /app/dagster_workspace.yaml
    ports:
      - 3001:3001
    env_file:
      - ./apps/backend/.env
    environment:
      - DAGSTER_HOME=/app/.dagster
    volumes:
      - ./apps/backend/.dagster:/app/.dagster
    depends_on:
      mongodb:
        condition: service_healthy
    restart: unless-stopped

  dagster-daemon:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    command: dagster-daemon run -w /app/dagster_workspace.yaml
    env_file:
      - ./apps/backend/.env
    environment:
      - DAGSTER_HOME=/app/.dagster
    volumes:
      - ./apps/backend/.dagster:/app/.dagster
    depends_on:
      mongodb:
        condition: service_healthy
      dagster-webserver:
        condition: service_started
    restart: unless-stopped

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - ./apps/frontend/.env
    depends_on:
      backend:
        condition: service_started
    restart: unless-stopped

  mongodb:
    image: mongodb/mongodb-atlas-local:latest
    ports:
      - 27017:27017
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
    volumes:
      - mongo_atlas_data:/data/db
      - mongo_atlas_config_data:/data/configdb
      - mongo_atlas_search_data:/data/mongot
    restart: unless-stopped

volumes:
  mongo_atlas_data:
  mongo_atlas_config_data:
  mongo_atlas_search_data:
